name: Deploy Pelican site to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  Deploy:
    uses: shivanisemwal/sitecontent/.github/workflows/makefile.yml@main
    permissions:
      contents: read
      pages: write
      id-token: write
