name: Deploy Pelican site to GitHub Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  Deploy:
    uses: shivanisemwal/sitecontent/.github/workflows/makefile.yml@c3df11d7aaf06089ab7e071b740fc53d2bda9c5a
    permissions:
      contents: read
      pages: write
      id-token: write
